name: Build Custom Kernel

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Pozwala ręcznie uruchomić workflow

jobs:
  build-kernel:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install build dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          build-essential \
          bc \
          bison \
          flex \
          libssl-dev \
          libelf-dev \
          dwarves \
          git \
          fakeroot \
          ncurses-dev \
          xz-utils \
          libpci-dev \
          libudev-dev

    - name: Download Linux kernel 6.12
      run: |
        wget https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.12.tar.xz
        tar xf linux-6.12.tar.xz
        cd linux-6.12

    - name: Copy custom kernel config
      run: |
        cp kernel-config/.config linux-6.12/.config

    - name: Prepare kernel configuration
      run: |
        cd linux-6.12
        # Ustaw wszystkie nowe opcje na domyślne wartości
        yes "" | make oldconfig

    - name: Show kernel version info
      run: |
        cd linux-6.12
        make kernelversion
        echo "Building kernel with config:"
        head -20 .config

    - name: Build kernel
      run: |
        cd linux-6.12
        # Użyj wszystkich dostępnych rdzeni
        make -j$(nproc) 
        
    - name: Build modules
      run: |
        cd linux-6.12
        make -j$(nproc) modules

    - name: Create build info
      run: |
        cd linux-6.12
        echo "Build completed at: $(date)" > build-info.txt
        echo "Kernel version: $(make kernelversion)" >> build-info.txt
        echo "Built on: $(uname -a)" >> build-info.txt
        echo "GCC version: $(gcc --version | head -1)" >> build-info.txt

    - name: Upload kernel image
      uses: actions/upload-artifact@v4
      with:
        name: kernel-bzImage
        path: linux-6.12/arch/x86/boot/bzImage
        retention-days: 30

    - name: Upload kernel modules
      uses: actions/upload-artifact@v4
      with:
        name: kernel-modules
        path: |
          linux-6.12/**/*.ko
          linux-6.12/modules.builtin
          linux-6.12/modules.order
        retention-days: 30

    - name: Upload build info
      uses: actions/upload-artifact@v4
      with:
        name: build-info
        path: linux-6.12/build-info.txt
        retention-days: 30

    - name: Show build summary
      run: |
        cd linux-6.12
        echo "=== Build Summary ==="
        echo "Kernel: $(file arch/x86/boot/bzImage)"
        echo "Size: $(du -h arch/x86/boot/bzImage)"
        echo "Modules built: $(find . -name "*.ko" | wc -l)"
        echo "Build time: $(date)"
