name: Build Linux Kernel RPMs

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout kernel source
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            bc \
            bison \
            flex \
            libssl-dev \
            libelf-dev \
            dwarves \
            rpm \
            fakeroot

      - name: Configure kernel (default defconfig)
        run: |
          make mrproper
          make defconfig

      - name: Build kernel RPM packages
        run: |
          make -j$(nproc) binrpm-pkg

      - name: Upload RPM artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-rpms
          path: ../*.rpm
