name: Build Custom Kernel RPM (Docker + Incremental)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-kernel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache zypper packages
        uses: actions/cache@v4
        with:
          path: /tmp/zypp-cache
          key: zypper-cache-${{ hashFiles('kernel-config/.config') }}
          restore-keys: zypper-cache-

      - name: Cache kernel build directory
        uses: actions/cache@v4
        with:
          path: /usr/src/linux-6.16.7-1-obj
          key: kernel-build-${{ hashFiles('kernel-config/.config') }}
          restore-keys: kernel-build-

      - name: Run incremental kernel build inside Docker
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          docker run --rm -t \
            -v ${{ github.workspace }}:/workspace \
            -v /tmp/zypp-cache:/var/cache/zypp \
            -w /workspace \
            opensuse/tumbleweed \
            /workspace/build-kernel.sh

      - name: Upload kernel RPMs
        uses: actions/upload-artifact@v4
        with:
          name: kernel-rpms
          path: kernel-config/x86_64/RPMS/*.rpm
