name: Build custom kernel RPM

on:
  workflow_dispatch:

jobs:
  build-kernel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker volumes
        run: |
          mkdir -p /tmp/zypp-cache

      - name: Build kernel inside Docker
        run: |
          docker run --rm -t \
            -v ${{ github.workspace }}:/workspace \
            -v /tmp/zypp-cache:/var/cache/zypp \
            -w /workspace \
            opensuse/tumbleweed \
            bash -c "./build-kernel.sh kernel-config/6.16.7-1-default.custom/current"

      - name: Upload RPMs as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-rpms
          path: /usr/src/packages/RPMS/x86_64/*.rpm
