name: Build Custom Kernel RPM

on:
  workflow_dispatch:

jobs:
  build-rpm:
    runs-on: ubuntu-latest
    container:
      image: opensuse/tumbleweed:latest
      options: --user root

    env:
      TZ: Europe/Warsaw

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install essential tools
      run: |
        zypper --non-interactive ref
        zypper --non-interactive install -y \
          bc bison flex gcc make ncurses-devel perl rpm-build rpm-sign wget tar xz

    - name: Run kernel build script
      run: |
        chmod +x build-kernel.sh
        ./build-kernel.sh "kernel-config/6.16.7-1-default.custom/current"

    - name: Upload built RPMs
      uses: actions/upload-artifact@v4
      with:
        name: custom-kernel-rpms
        path: /usr/src/packages/RPMS/x86_64/*.rpm
