name: Build Linux Kernel

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Cache dla ccache
      - name: Setup ccache
        uses: actions/cache@v4
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-ccache-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-ccache-${{ github.ref }}
            ${{ runner.os }}-ccache-

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential flex bison libssl-dev \
            libncurses-dev libelf-dev dwarves ccache

      - name: Download Linux kernel source
        run: |
          wget https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.12.1.tar.xz
          tar -xvf linux-6.12.1.tar.xz
          cd linux-6.12.1
          echo "KERNEL_SRC=$PWD" >> $GITHUB_ENV

      - name: Configure kernel
        run: |
          cd $KERNEL_SRC
          if [ -f "${GITHUB_WORKSPACE}/kernel.config" ]; then
            echo "Using custom kernel.config"
            cp "${GITHUB_WORKSPACE}/kernel.config" .config
          else
            echo "No custom config found, using defconfig"
            make defconfig
          fi

      - name: Build kernel
        run: |
          cd $KERNEL_SRC
          export PATH="/usr/lib/ccache:$PATH"
          export CC="ccache gcc"
          export CXX="ccache g++"
          make -j$(nproc)

      - name: Package kernel
        run: |
          cd $KERNEL_SRC
          make -j$(nproc) bindeb-pkg

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-packages
          path: |
            ../*.deb
