name: Build Custom Kernel 6.16.7 RPM

on:
  workflow_dispatch:

env:
  KERNEL_VERSION: 6.16.7

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential libncurses-dev bison flex libssl-dev libelf-dev \
            fakeroot dpkg-dev rpm wget xz-utils

      - name: Download kernel sources
        run: |
          wget https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-${KERNEL_VERSION}.tar.xz
          tar -xf linux-${KERNEL_VERSION}.tar.xz

      - name: Build kernel RPMs
        run: |
          cd linux-${KERNEL_VERSION}
          make -j$(nproc) binrpm-pkg \
            LOCALVERSION=-custom \
            RPMOPTS="--define 'dist .custom'"

      - name: Upload kernel RPMs
        uses: actions/upload-artifact@v4
        with:
          name: kernel-rpms
          path: ~/rpmbuild/RPMS/x86_64/*.rpm
