name: Build Linux Kernel RPM

on:
  workflow_dispatch:

jobs:
  build-rpm:
    runs-on: ubuntu-latest

    env:
      KERNEL_VERSION: 6.12

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential bc flex bison libssl-dev libncurses-dev \
            fakeroot dwarves rpm libelf-dev libdw-dev libz-dev git curl

      - name: Download Linux kernel source
        run: |
          curl -LO https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-${KERNEL_VERSION}.tar.xz
          tar -xf linux-${KERNEL_VERSION}.tar.xz

      - name: Build kernel RPM packages
        run: |
          cd linux-${KERNEL_VERSION}
          # Jeśli nie ma config, użyj defconfig
          cp /boot/config-$(uname -r) .config || make defconfig
          yes "" | make oldconfig
          make -j$(nproc) binrpm-pkg

      - name: Copy RPMs to artifacts folder
        run: |
          mkdir -p artifacts/kernel-rpms
          cp linux-${KERNEL_VERSION}/rpmbuild/RPMS/x86_64/*.rpm artifacts/kernel-rpms/ || echo "No RPMs to copy"

      - name: Upload RPM artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-rpms
          path: artifacts/kernel-rpms/*.rpm
          retention-days: 30

      - name: Commit RPMs to repo
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          mkdir -p kernel-rpms
          cp artifacts/kernel-rpms/*.rpm kernel-rpms/ || echo "No RPMs to copy"
          git add kernel-rpms
          git commit -m "Add built kernel RPMs" || echo "No changes to commit"
          git push
