name: Build Linux Kernel RPMs (with more deps + debug)

on:
  workflow_dispatch:

jobs:
  build_rpm:
    runs-on: ubuntu-latest

    env:
      KERNEL_VERSION: 6.12

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential bc bison flex libssl-dev libncurses-dev \
            libelf-dev libdw-dev libelf1 zlib1g-dev xz-utils \
            liblzma-dev rpm fakeroot dwarves git perl python3 binutils

      - name: Download Linux kernel source
        run: |
          curl -LO https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-${KERNEL_VERSION}.tar.xz
          tar -xf linux-${KERNEL_VERSION}.tar.xz

      - name: Configure kernel
        run: |
          cd linux-${KERNEL_VERSION}
          cp /boot/config-$(uname -r) .config || make defconfig
          yes "" | make oldconfig

      - name: Build kernel RPM packages with debug
        run: |
          cd linux-${KERNEL_VERSION}
          make -j$(nproc) binrpm-pkg || { echo "build failed, dumping last lines of log"; tail -n100 build.log; exit 1; }

      - name: Copy RPMs to artifacts folder
        run: |
          mkdir -p kernel-rpms
          cp linux-${KERNEL_VERSION}/rpmbuild/RPMS/x86_64/*.rpm kernel-rpms/ || echo "No RPMs found"

      - name: Verify RPMs
        run: |
          if [ -z "$(ls kernel-rpms/*.rpm 2>/dev/null)" ]; then
            echo "ERROR: No RPMs built!"
            exit 1
          else
            echo "RPMs present:"
            ls -lh kernel-rpms/
          fi

      - name: Upload RPM artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-rpms
          path: kernel-rpms/*.rpm
          retention-days: 30

      - name: Commit RPMs to repo
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add kernel-rpms/*.rpm
          git diff --cached --quiet || git commit -m "Add built kernel RPMs version ${KERNEL_VERSION}"
          git push
