name: Build Linux Kernel RPM

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      KERNEL_VERSION: 6.12

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses-dev bison flex libssl-dev libelf-dev \
              rpm bc dwarves

      - name: Download kernel source
        run: |
          wget https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-${KERNEL_VERSION}.tar.xz
          tar -xf linux-${KERNEL_VERSION}.tar.xz

      - name: Prepare kernel config
        run: |
          cd linux-${KERNEL_VERSION}
          cp /boot/config-$(uname -r) .config || make defconfig
          yes "" | make olddefconfig

          # 🔧 Disable trusted/revocation keys (fixes canonical-certs.pem error)
          sed -i 's|CONFIG_SYSTEM_TRUSTED_KEYS=.*|CONFIG_SYSTEM_TRUSTED_KEYS=""|' .config
          sed -i 's|CONFIG_SYSTEM_REVOCATION_KEYS=.*|CONFIG_SYSTEM_REVOCATION_KEYS=""|' .config

      - name: Build RPM packages
        run: |
          cd linux-${KERNEL_VERSION}
          make -j$(nproc) binrpm-pkg

      - name: Collect RPMs
        run: |
          mkdir -p artifacts/rpm
          find .. -maxdepth 1 -type f -name "*.rpm" -exec cp {} artifacts/rpm/ \;

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-rpms
          path: artifacts/rpm/

      - name: Push RPMs to repository
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          mkdir -p artifacts/rpm
          git pull
          git add artifacts/rpm
          git commit -m "Add kernel RPM build for ${KERNEL_VERSION}" || echo "No changes to commit"
          git push
