name: Build Linux Kernel RPMs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  KERNEL_VERSION: 6.12
  RPM_OUTPUT_DIR: rpmbuild/RPMS/x86_64

jobs:
  build-kernel:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential libncurses-dev bison flex libssl-dev libelf-dev \
            rpm curl bc ccache git dwarves

      - name: Cache ccache
        uses: actions/cache@v3
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-ccache-${{ hashFiles('**/Makefile') }}
          restore-keys: |
            ${{ runner.os }}-ccache-

      - name: Download Linux Kernel
        run: |
          curl -LO https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-${KERNEL_VERSION}.tar.xz
          tar -xf linux-${KERNEL_VERSION}.tar.xz

      - name: Prepare .config
        run: |
          cd linux-${KERNEL_VERSION}
          # Tutaj możesz podać własny konfig: 
          # cp /path/to/custom.config .config || make defconfig
          make defconfig

      - name: Build RPMs
        run: |
          cd linux-${KERNEL_VERSION}
          make -j$(nproc) binrpm-pkg

      - name: Upload RPMs as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-rpms
          path: ${{ env.RPM_OUTPUT_DIR }}/*.rpm

      - name: Commit & push RPMs to repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          mkdir -p kernel-rpms
          cp ${{ env.RPM_OUTPUT_DIR }}/*.rpm kernel-rpms/
          git add kernel-rpms/
          git commit -m "Add built kernel RPMs"
          git push || echo "No changes to push"
