name: Build Kernel 6.12 RPMs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  KERNEL_VERSION: 6.12

jobs:
  build-kernel:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential libncurses-dev bison flex libssl-dev libelf-dev \
            rpm curl bc ccache git dwarves

      - name: Cache ccache
        uses: actions/cache@v3
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-ccache-${{ hashFiles('**/Makefile') }}
          restore-keys: |
            ${{ runner.os }}-ccache-

      - name: Download Linux Kernel
        run: |
          curl -LO https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-${KERNEL_VERSION}.tar.xz
          tar -xf linux-${KERNEL_VERSION}.tar.xz

      - name: Prepare .config
        run: |
          cd linux-${KERNEL_VERSION}
          # Możesz podać własny config zamiast defconfig:
          # cp /path/to/custom.config .config || make defconfig
          make defconfig

      - name: Build binary RPMs
        run: |
          cd linux-${KERNEL_VERSION}
          make -j$(nproc) binrpm-pkg

      - name: Upload RPMs as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-rpms
          path: linux-${{ env.KERNEL_VERSION }}/rpmbuild/RPMS/x86_64/*.rpm
