name: Build Linux Kernel RPM (6.16.7)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      KERNEL_VERSION: 6.16.7
      KERNEL_RELEASE: 1
      LOCALVERSION: -custom
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential libncurses-dev bison flex libssl-dev libelf-dev \
            dwarves ccache bc fakeroot rpm gpg

      - name: Import GPG key
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import
          KEYGRIP=$(gpg --list-secret-keys --with-keygrip | grep Keygrip | awk '{print $3}')
          printf "pinentry-mode loopback\npassphrase $GPG_PASSPHRASE\n" > ~/.gnupg/gpg.conf
          printf "allow-preset-passphrase\n" > ~/.gnupg/gpg-agent.conf
          gpg-connect-agent reloadagent /bye
          /usr/lib/gnupg/gpg-preset-passphrase --preset --passphrase "$GPG_PASSPHRASE" "$KEYGRIP"

      - name: Download kernel source
        run: |
          wget https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-${KERNEL_VERSION}.tar.xz
          tar -xf linux-${KERNEL_VERSION}.tar.xz

      - name: Copy current config
        run: |
          cp /usr/src/linux-headers-$(uname -r)/.config linux-${KERNEL_VERSION}/ || true

      - name: Build kernel and RPM
        run: |
          cd linux-${KERNEL_VERSION}
          # Build kernel first
          make -j"$(nproc)"
          # Then create RPM packages without rebuilding
          make rpm-pkg \
            LOCALVERSION=${LOCALVERSION} \
            KDEB_PKGVERSION=${KERNEL_VERSION}-${KERNEL_RELEASE} \
            RPMOPTS="--define 'dist .custom' --define '_rpmdir $HOME/rpmbuild/RPMS/x86_64'"

      - name: Sign RPM packages
        run: |
          for rpm in $HOME/rpmbuild/RPMS/x86_64/*.rpm; do
            rpmsign --addsign "$rpm"
          done

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-rpms
          path: ~/rpmbuild/RPMS/x86_64/*.rpm
