name: Build Custom Kernel RPM (Docker)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-kernel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build kernel inside Docker
        run: |
          docker run --rm -t \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            opensuse/tumbleweed \
            /bin/bash -c "
              set -e

              echo 'Adding standard Tumbleweed repositories...'
              zypper ar -f http://download.opensuse.org/tumbleweed/repo/oss/ repo-oss
              zypper ar -f http://download.opensuse.org/tumbleweed/repo/non-oss/ repo-non-oss
              zypper ar -f http://download.opensuse.org/update/tumbleweed/ repo-update

              echo 'Refreshing repositories...'
              zypper ref

              echo 'Installing build tools...'
              zypper -n in -t pattern devel_basis
              zypper -n in bc bison elfutils-devel flex gcc git make ncurses-devel perl rpm-build rpm-sign wget

              echo 'Copying custom kernel config...'
              mkdir -p /usr/src/linux-6.16.7-1-obj/x86_64/default
              cp kernel-config/.config /usr/src/linux-6.16.7-1-obj/x86_64/default/.config

              echo 'Building kernel RPMs...'
              cd /usr/src/linux-6.16.7-1-obj
              make -j\$(nproc) rpm

              echo 'Importing GPG key for signing...'
              echo \"${{ secrets.GPG_PRIVATE_KEY }}\" | gpg --batch --import

              echo 'Signing RPMs...'
              for rpm in x86_64/RPMS/*.rpm; do
                rpmsign --addsign \$rpm
              done

              echo 'Kernel RPMs build complete'
            "

      - name: Upload kernel RPMs
        uses: actions/upload-artifact@v4
        with:
          name: kernel-rpms
          path: |
            kernel-config/x86_64/RPMS/*.rpm
