name: Build Custom Kernel (openSUSE Tumbleweed)

on:
  workflow_dispatch:
    inputs:
      enable_signing:
        description: "Enable kernel module signing (true/false)"
        required: true
        default: "false"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ENABLE_SIGNING: ${{ github.event.inputs.enable_signing }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential libncurses-dev bison flex libssl-dev libelf-dev wget bc cpio

      - name: Download kernel source
        run: |
          KERNEL_VERSION=6.16.7
          wget https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-$KERNEL_VERSION.tar.xz
          tar -xvf linux-$KERNEL_VERSION.tar.xz
          mv linux-$KERNEL_VERSION linux
          ls -lah

      - name: Copy SUSE kernel config
        run: |
          cp /usr/src/linux-$(uname -r | cut -d- -f1)-obj/x86_64/default/.config linux/.config || true

      - name: Configure signing
        run: |
          cd linux
          if [ "$ENABLE_SIGNING" = "true" ]; then
            echo "⚡ Enabling module signing..."
            scripts/config --enable MODULE_SIG
            scripts/config --enable SYSTEM_TRUSTED_KEYS
            scripts/config --enable SYSTEM_REVOCATION_KEYS
          else
            echo "⚡ Disabling module signing..."
            scripts/config --disable MODULE_SIG
            scripts/config --disable SYSTEM_TRUSTED_KEYS
            scripts/config --disable SYSTEM_REVOCATION_KEYS
          fi
          yes "" | make olddefconfig

      - name: Build kernel
        run: |
          cd linux
          make -j$(nproc)

      - name: Build kernel modules
        run: |
          cd linux
          make -j$(nproc) modules

      - name: Install modules
        run: |
          cd linux
          sudo make modules_install

      - name: Install kernel
        run: |
          cd linux
          sudo make install

      - name: Archive kernel artifacts
        uses: actions/upload-artifact@v3
        with:
          name: suse-kernel
          path: |
            /boot/vmlinuz-*
            /boot/initrd-*
            /lib/modules/*
