name: Build Kernel RPM

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run kernel build in openSUSE Tumbleweed
        run: |
          docker run --rm -t \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            opensuse/tumbleweed \
            /bin/bash -c "chmod +x build-kernel.sh && ./build-kernel.sh"

      - name: Upload RPM artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-rpms
          path: /usr/src/packages/RPMS/x86_64/*.rpm
