name: Build Linux Kernel RPM

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: opensuse/tumbleweed
    env:
      KERNEL_VERSION: 6.16.7
      KERNEL_RELEASE: 1
      LOCALVERSION: -custom
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install build dependencies
        run: |
          sudo zypper refresh
          sudo zypper install -y \
            make gcc ncurses-devel bison flex libopenssl-devel libelf-devel \
            rpm-build ccache bc gpg2 perl wget gzip tar fakeroot perl-Text-Template \
            git python3 rsync dwarves

      - name: Prepare custom .config
        run: |
          cd linux-${KERNEL_VERSION}
          cp $GITHUB_WORKSPACE/kernel-config/6.16.7-1-default.custom/current .config
          make olddefconfig

      - name: Build kernel and RPM packages
        run: |
          cd linux-${KERNEL_VERSION}
          make -j$(nproc) rpm-pkg \
            LOCALVERSION=${LOCALVERSION} \
            KDEB_PKGVERSION=${KERNEL_VERSION}-${KERNEL_RELEASE} \
            RPMOPTS="--define 'dist .custom' --define '_rpmdir $HOME/rpmbuild/RPMS/x86_64'"

      - name: Upload RPM artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-rpms
          path: linux-${KERNEL_VERSION}/rpmbuild/RPMS/x86_64/
