name: Build Custom Kernel RPM

on:
  workflow_dispatch:
    inputs:
      kernel_config:
        description: "Path to kernel config"
        required: true
        default: "kernel-config/6.16.7-1-default.custom/current"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Write GPG key and passphrase to files
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" > gpg-private.key
          echo "${{ secrets.GPG_PASSPHRASE }}" > gpg-passphrase.txt

      - name: Build kernel RPM inside Docker
        run: |
          docker run --rm -t \
            -v "${{ github.workspace }}":/workspace \
            -v "${{ github.workspace }}/packages":/usr/src/packages \
            -v /tmp/zypp-cache:/var/cache/zypp \
            -w /workspace \
            -v "${{ github.workspace }}/gpg-private.key:/tmp/gpg-private.key:ro" \
            -v "${{ github.workspace }}/gpg-passphrase.txt:/tmp/gpg-passphrase.txt:ro" \
            opensuse/tumbleweed \
            /workspace/build-kernel.sh "${{ github.event.inputs.kernel_config }}"

      - name: Upload RPM artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-rpms
          path: packages/RPMS/**/*.rpm
