name: Build Custom Kernel RPM

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run kernel build inside Docker
        run: |
          docker run --rm -t \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            opensuse/tumbleweed \
            /workspace/build-kernel.sh kernel-config/6.16.7-1-default.custom/current

      - name: Upload RPMs
        uses: actions/upload-artifact@v4
        with:
          name: custom-kernel-rpms
          path: |
            /workspace/usr/src/packages/RPMS/**/*.rpm
