name: Build Custom Kernel RPM

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker container and build
        run: |
          docker run --rm -t \
            -v ${{ github.workspace }}:/workspace \
            -v /tmp/zypp-cache:/var/cache/zypp \
            -w /workspace \
            opensuse/tumbleweed \
            bash /workspace/build-kernel.sh kernel-config/6.16.7-1-default.custom/current

      - name: Upload built RPMs
        uses: actions/upload-artifact@v4
        with:
          name: custom-kernel-rpms
          path: /usr/src/packages/RPMS/**/*.rpm
