name: Build Linux Kernel RPM

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # potrzebne do automatycznego push

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential bc flex bison libssl-dev libncurses-dev \
            fakeroot dwarves rpm libelf-dev libdw-dev libelf1 git curl xz-utils

      - name: Download Linux kernel source
        run: |
          KERNEL_VERSION=6.12
          curl -LO https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-$KERNEL_VERSION.tar.xz
          tar -xvf linux-$KERNEL_VERSION.tar.xz

      - name: Configure kernel
        run: |
          cd linux-6.12
          cp /boot/config-$(uname -r) .config || make defconfig
          yes "" | make oldconfig

      - name: Build kernel RPM packages
        run: |
          cd linux-6.12
          make -j$(nproc) binrpm-pkg

      - name: Copy RPMs to artifacts directory
        run: |
          mkdir -p artifacts/kernel
          cp linux-6.12/rpmbuild/RPMS/x86_64/*.rpm artifacts/kernel/ || echo "No RPMs to copy"

      - name: Commit and push RPMs to repository
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add artifacts/kernel/*.rpm
          git commit -m "Add built kernel RPMs" || echo "Nothing to commit"
          git push

      - name: Save build info
        run: |
          cd linux-6.12
          echo "Build completed at: $(date)" > build-info.txt
          echo "Kernel version: $(make kernelversion)" >> build-info.txt
          echo "Built on: $(uname -a)" >> build-info.txt
          echo "GCC version: $(gcc --version | head -1)" >> build-info.txt

      - name: Upload RPM artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-rpms
          path: artifacts/kernel/*.rpm
          retention-days: 30

      - name: Upload build info
        uses: actions/upload-artifact@v4
        with:
          name: build-info
          path: linux-6.12/build-info.txt
          retention-days: 30
